Completed statistics Screen
traccar/traccar-web pull request #819
Opened 2021-02-19 09:04 UTC by mail2bishnoi

Hi Anton,

Something went wrong with the old statistics branch, please review this for the reverted changes.

2021-02-19 17:33 UTC, tananaev requested changes
I think there is some error again.

2021-02-20 10:06 UTC, mail2bishnoi commented
Sorry, Anton, I could not find an error.

2021-02-20 16:15 UTC, tananaev commented
You did the opposite of what needs to be done. You removed statistics page, but left filter changes. Have you looked at the diff?

2021-02-22 06:03 UTC, mail2bishnoi commented
Hi Anton,

I have added the StatisticsPage.js. I think now its complete.

2021-02-22 06:05 UTC, tananaev commented
Why are there still changes in `ReportFilter.js`?

2021-02-22 06:05 UTC, tananaev commented
Please take your time and carefully look at the pull request before asking for another review.

2021-02-22 15:56 UTC, mail2bishnoi commented
Hi Anton,

I think there is something misunderstood.
When I completely separated the StatisticsPage then you asked me to revert the changes. I understood that revert the changes to use ReporFilter.js with showDevices configuration.
Therefore now ReportFilter.js has changes.

2021-02-22 15:59 UTC, mail2bishnoi commented
My questions

1. Should I sperate the StatisticsPage completely means keeping date filter in the same file?
2.  Should I use ReportFilter.js with showDevices param?

2021-02-22 16:17 UTC, tananaev commented
When I asked you to revert, you had those changes. So by revert I meant remove the changes.

2021-02-24 06:45 UTC, mail2bishnoi commented
Hi Anton,

Again reverted the changes.  Removed configuration from ReportFilter.js. And StatisticsPage has its own period filter.

Sorry, this small PR took longer than expected time due to my misunderstanding. Hope everything is ok now.

2021-02-24 07:05 UTC, tananaev commented on modern/src/admin/StatisticsPage.js
> +    </FormControl>
There are some problems with indentation. Please make sure formatting everywhere is correct.

2021-02-24 07:05 UTC, tananaev commented on modern/src/reports/ReportFilter.js
> +        <ButtonGroup color="primary" orientation="vertical" disabled={ !deviceId }>
Please revert this as well.

2021-02-24 08:19 UTC, mail2bishnoi commented
Done.

2021-02-24 17:54 UTC, merged

2021-02-24 17:54 UTC, tananaev commented
Merged, thank you.